"""Constants used throughout AgentChef."""

# MCP Protocol
MCP_PORT = 50505

# Configuration
CONFIG_SECTION = "agentchef"
DEFAULT_CONFIG_FILENAME = "agentchef.ini"

# Config keys
CONFIG_KEY_DATA_DIR = "data_dir"
CONFIG_KEY_LOG_LEVEL = "log_level"
CONFIG_KEY_MAX_RETRIES = "max_retries"
CONFIG_KEY_TIMEOUT = "timeout"
CONFIG_KEY_USER_AGENT = "user_agent"
CONFIG_KEY_GITHUB_TOKEN = "github_token"

# Default values
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_MAX_RETRIES = 3
DEFAULT_TIMEOUT = 30
DEFAULT_USER_AGENT = "AgentChef/1.0"

# Environment variables 
ENV_DATA_DIR = "AGENTCHEF_DATA_DIR"
ENV_LOG_LEVEL = "AGENTCHEF_LOG_LEVEL"
ENV_MAX_RETRIES = "AGENTCHEF_MAX_RETRIES"
ENV_TIMEOUT = "AGENTCHEF_TIMEOUT"
ENV_USER_AGENT = "AGENTCHEF_USER_AGENT"
ENV_GITHUB_TOKEN = "AGENTCHEF_GITHUB_TOKEN"

# Return codes
SUCCESS = 0
ERROR = 1